image:
  repository: "europe-west1-docker.pkg.dev/stape-development/mcp-ga"
  name: "mcp-ga"
  tag: "latest"

host: "example.com"

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
