apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  commonName: mcp-ga.{{ .Values.domain }}
  secretName: {{ .Release.Name }}-certificate
  dnsNames:
    - mcp-ga.{{ .Values.domain }}
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
