apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}
spec:
  commonName: {{ .Values.host }}
  secretName: {{ .Release.Name }}-certificate
  dnsNames:
    - {{ .Values.host }}
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
